### ISSUE TITLE
Mac Notification with 0 inbox

### ISSUE THREAD

**Issue by RJClarke** [3axap4eHko/OWA-Notifier#50]
I receive a notification when I get an email. But after checking my mail, the notification will continuing popping up from the Mac OS seemingly at random intervals over the next 5 minutes....

![screen shot 2015-08-19 at 3 31 40 pm](https://cloud.githubusercontent.com/assets/2575308/9368469/1753faac-4689-11e5-8bf6-d2deb104e6fd.png)

**Comment by 3axap4eHko** [comment]
Fixed in 3.0.1.7

**Comment by RJClarke** [comment]
I'm still getting a flurry of notifications when I have no new mail. Nothing stops it...
